set_property SRC_FILE_INFO {cfile:D:/Vivado_Project/CNN_convo/CNN_convo.srcs/constrs_1/new/cons.xdc rfile:../../../CNN_convo.srcs/constrs_1/new/cons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports reset_n]
